development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: layout_development
  pool: 5
  username: root
  password: secret
  host: db
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: layout_test
  pool: 5
  username: root
  password: secret
  host: db
